services:
  network-deploy-service:
    networks:
      - eazybytes-network
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_PROFILES_ACTIVE: default
  config-server-base-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://eazybytes-config-server:8071/