services:
  network-deploy-service:
    networks:
      - eazybytes-network
      
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_PROFILES_ACTIVE: default
  
  eurekaserver-base-config:
    depends_on:
      eazybytes-config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
  
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      eazybytes-config-server:
        condition: service_healthy
      eazybytes-eurekaserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
  
  