services:
  read:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=read"
    container_name: eazybytes-grafana_loki_read
    ports:
      - 3101:3100
      - 7946
      - 9095
    volumes:
      - ../observability/loki/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: &loki-dns
      eazybytes-network:
        aliases:
          - loki

  write:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=write"
    container_name: eazybytes-grafana_loki_write
    ports:
      - 3102:3100
      - 7946
      - 9095
    volumes:
      - ../observability/loki/loki-config.yaml:/etc/loki/config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio
    networks:
      <<: *loki-dns

  alloy:
    image: grafana/alloy:latest
    container_name: eazybytes-grafana_alloy
    volumes:
      - ../observability/alloy/alloy-local-config.yaml:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:  run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - 12345:12345
    depends_on:
      - gateway
    networks:
      - eazybytes-network

  minio:
    image: minio/minio
    container_name: eazybytes-minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - 9000
    volumes:
      - ./.data/minio:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5
    networks:
      - eazybytes-network
      
  prometheus:
    image: prom/prometheus:latest
    container_name: eazybytes-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../observability/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - eazybytes-network

  grafana:
    image: grafana/grafana:latest
    container_name: eazybytes-grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - gateway
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://gateway:3100
            jsonData:
              httpHeaderName1: "X-Scope-OrgID"
            secureJsonData:
              httpHeaderValue1: "tenant1"
          - name: Prometheus
            type: prometheus
            uid: prometheus
            url: http://prometheus:9090
            access: proxy
            orgId: 1
            basicAuth: false
            isDefault: false
            version: 1
            editable: true
            jsonData:
              httpMethod: GET
        EOF
        /run.sh
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eazybytes-network

  backend:
    image: grafana/loki:latest
    container_name: eazybytes-grafana_loki_backend
    volumes:
      - ../observability/loki/loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    depends_on:
      - gateway
    networks:
      - eazybytes-network
    
  gateway:
    image: nginx:latest
    container_name: eazybytes-gateway_nginx
    depends_on:
      - read
      - write
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/nginx.conf
        user  nginx;
        worker_processes  5;  ## Default: 1

        events {
          worker_connections   1000;
        }

        http {
          resolver 127.0.0.11;

          server {
            listen             3100;

            location = / {
              return 200 'OK';
              auth_basic off;
            }

            location = /api/prom/push {
              proxy_pass       http://write:3100\$$request_uri;
            }

            location = /api/prom/tail {
              proxy_pass       http://read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }

            location ~ /api/prom/.* {
              proxy_pass       http://read:3100\$$request_uri;
            }

            location = /loki/api/v1/push {
              proxy_pass       http://write:3100\$$request_uri;
            }

            location = /loki/api/v1/tail {
              proxy_pass       http://read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }

            location ~ /loki/api/.* {
              proxy_pass       http://read:3100\$$request_uri;
            }
          }
        }
        EOF
        /docker-entrypoint.sh nginx -g "daemon off;"
    ports:
      - "3100:3100"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eazybytes-network
  
  eazybytes-rabbitmq:
    image: "rabbitmq:4-management"
    container_name: eazybytes-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - eazybytes-network
      
  eazybytes-redis:
    image: "redis"
    container_name: eazybytes-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    networks:
      - eazybytes-network

  eazybytes-config-server:
    image: "maleeshasa/eazybytes-configserver:s11"
    container_name: eazybytes-config-server
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: configserver
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq
      SPRING_PROFILES_ACTIVE: default
    networks:
      - eazybytes-network

  eazybytes-eurekaserver:
    image: "maleeshasa/eazybytes-eurekaserver:s11"
    container_name: eazybytes-eurekaserver
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
      eazybytes-config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      CONFIG_SERVER_URL: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
      EUREKA_INSTANCE_HOSTNAME: eazybytes-eurekaserver
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq
    networks:
      - eazybytes-network
      
  eazybytes-accounts:
    image: "maleeshasa/eazybytes-accounts:s11"
    container_name: eazybytes-accounts
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
      eazybytes-eurekaserver:
        condition: service_healthy
      eazybytes-config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: accounts
      CONFIG_SERVER_URL: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq
    networks:
      - eazybytes-network
      
  eazybytes-loans:
    image: "maleeshasa/eazybytes-loans:s11"
    container_name: eazybytes-loans
    ports:
      - "9091:9091"
    healthcheck:
      test: "curl --fail --silent localhost:9091/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
      eazybytes-eurekaserver:
        condition: service_healthy
      eazybytes-config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: loans
      CONFIG_SERVER_URL: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq
    networks:
      - eazybytes-network

  eazybytes-cards:
    image: "maleeshasa/easybytes-cards:s11"
    container_name: eazybytes-cards
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
      eazybytes-eurekaserver:
        condition: service_healthy
      eazybytes-config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: cards
      CONFIG_SERVER_URL: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq
    networks:
      - eazybytes-network

  eazybytes-gatewayserver:
    image: "maleeshasa/eazybytes-gatewayserver:s11"
    container_name: eazybytes-gatewayserver
    ports:
      - "8081:8081"
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
      eazybytes-eurekaserver:
        condition: service_healthy
      eazybytes-config-server:
        condition: service_healthy
      eazybytes-accounts:
        condition: service_healthy
      eazybytes-cards:
        condition: service_healthy
      eazybytes-loans:
        condition: service_healthy
      eazybytes-redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: gatewayserver
      CONFIG_SERVER_URL: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    networks:
      - eazybytes-network
    
networks:
  eazybytes-network:
    name: eazybytes-network
    driver: bridge
