services:
  eazybytes-rabbitmq:
    image: "rabbitmq:4-management"
    container_name: eazybytes-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  eazybytes-config-server:
    image: "maleeshasa/eazybytes-configserver:v3"
    container_name: eazybytes-config-server
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: configserver
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq
      SPRING_PROFILES_ACTIVE: default

  eazybytes-eurekaserver:
    image: "maleeshasa/eazybytes-eurekaserver:v3"
    container_name: eazybytes-eurekaserver
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
      eazybytes-config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      CONFIG_SERVER_URL: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
      EUREKA_INSTANCE_HOSTNAME: eazybytes-eurekaserver
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq
      SPRING_PROFILES_ACTIVE: native
      
  eazybytes-accounts:
    image: "maleeshasa/eazybytes-accounts:v3"
    container_name: eazybytes-accounts
    ports:
      - "8080:8080"
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
      eazybytes-eurekaserver:
        condition: service_healthy
      eazybytes-config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: accounts
      CONFIG_SERVER_URL: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq

  eazybytes-accounts_1:
    image: "maleeshasa/eazybytes-accounts:v3"
    container_name: eazybytes-accounts_1
    ports:
      - "8081:8080"
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
      eazybytes-eurekaserver:
        condition: service_healthy
      eazybytes-config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: accounts
      CONFIG_SERVER_URL: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq
      
  eazybytes-loans:
    image: "maleeshasa/eazybytes-loans:v3"
    container_name: eazybytes-loans
    ports:
      - "9091:9091"
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
      eazybytes-eurekaserver:
        condition: service_healthy
      eazybytes-config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: loans
      CONFIG_SERVER_URL: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq

  eazybytes-cards:
    image: "maleeshasa/easybytes-cards:v3"
    container_name: eazybytes-cards
    ports:
      - "8090:8090"
    depends_on:
      eazybytes-rabbitmq:
        condition: service_healthy
      eazybytes-eurekaserver:
        condition: service_healthy
      eazybytes-config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: cards
      CONFIG_SERVER_URL: http://eazybytes-config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eazybytes-eurekaserver:8070/eureka/
      SPRING_RABBITMQ_HOST: eazybytes-rabbitmq
      
networks:
  eazybytes-network:
    driver: bridge
